### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by luisdavim** [kontena/chpharos#39]
I ran:
```
brew install kontena/chpharos/chpharos
```
but `chpharos` was not installed, only `chpharos-exec`

and if I try to run:
```
$ chpharos-exec -i latest
error: You need to log in. Use: chpharos login
chpharos-exec: installation of version latest failed
```

I just want to be able to use `pharos up -c cluster.yml` with some local machines.

**Comment by nevalla** [comment]
Did you follow these instructions?
```
$ brew install kontena/chpharos/chpharos
....
==> Caveats
Add the following to the ~/.bash_profile or ~/.zshrc file:
  source /usr/local/opt/chpharos/share/chpharos/chpharos.sh

To enable auto-switching of Pharos versions specified by .pharos-version files,
add the following to ~/.bash_profile or ~/.zshrc:
  chpharos auto

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
```

**Comment by luisdavim** [comment]
ok, after running `source /usr/local/opt/chpharos/share/chpharos/chpharos.sh` I cant run `chpharos`

but still:
```
$ chpharos install latest
error: You need to log in. Use: chpharos login
```

why do I need to login if all I want is to use it locally?

**Comment by nevalla** [comment]
Meanwhile you can download `pharos-cluster` binary manually by following these instructions: https://pharos.sh/docs/tools/pharos.html#other-installation-methods

You might want to rename `pharos-cluster` binary as `pharos` to match better with documentation.

**Comment by luisdavim** [comment]
Thanks, that solves my issue.
